
tables_to_get = [
    'charge_drawn_from_network',
    'next_leg_charge_from_network',
    'connectivity_per_location',
    'maximal_delivered_power_per_location',
    'maximal_received_power_per_location',
    'vehicle_discharge_power_per_location',
    'discharge_power_to_network_per_location',
]
quantity_names = [
    'Reference charge drawen from network (kWh)',
    'Demand for next leg (kWh) (fom network)',
    'Connected vehicles (%)',
    'Connected Power from Network (kW)',
    'Connected Power to Vehicles (kW)',
    'Vehicle Discharge Power (kW)',
    'Discharge Power to Network (kW)',


]
index_is_expanded = [
    true, 
    false,
    false,
    false,
    false,
    false,
    false
]

base_index = ['Time Tag']
expanded_index = ['Time Tag', 'Hour number', 'SPINE hour number']

profiles_groupfile_root = 'profiles'

